elasticsearch:
  build: ./apolodoro-backend/.
  ports:
   - "9200:9200"

backend:
  build: ./apolodoro-backend/.
  ports:
   - "8080:8080"
  links:
   - elasticsearch

nginx:
  image: "nginx:latest"
  volumes:
   - ./apolodoro-react-frontend/build:/usr/share/nginx/html
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=localhost
   - NGINX_PORT=80
  command: /bin/bash -c "nginx -g 'daemon off;'"
  links:
   - backend

selenium:
    image: selenium/standalone-firefox
    environment:
        # Required to avoid container startup hanging sometimes in
        # some environments
        JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
    links:
        - nginx
    ports:
        - "4444:4444"